priz_user:
    resource: "@PrizUserBundle/Controller/"
    type:     annotation
    prefix:   /

book_manager:
    resource: "@BookManagerBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/authorize.xml"

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

payum_payout:
    resource: "@PayumBundle/Resources/config/routing/payout.xml"

payum_refund:
    resource: "@PayumBundle/Resources/config/routing/refund.xml"

payum_sync:
    resource: "@PayumBundle/Resources/config/routing/sync.xml"



